# Generated by Django 4.2.1 on 2024-09-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='husband',
            name='m_count',
        ),
    ]
