# Generated by Django 4.2.1 on 2024-09-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_husband_m_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='m_count2',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
