# Generated by Django 4.2.1 on 2024-09-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_remove_husband_m_count2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='tags',
        ),
    ]
