# Generated by Django 4.2.1 on 2024-09-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_remove_women_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='women.tagarticle'),
        ),
    ]
